### ISSUE TITLE
Blender 5.0 Create UV Mesh Broken

### ISSUE THREAD

**Issue by gulagenabler** [SavMartin/TexTools-Blender#272]
<img width="1486" height="954" alt="Image" src="https://github.com/user-attachments/assets/8c3cd768-a3cf-47ff-ad82-3fcb9e1593e2" />

Python: Traceback (most recent call last):
  File "C:\Users\Roy\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\TexTools_1_6_1\op_meshtex_create.py", line 28, in execute
    return create_uv_mesh(self, context, bpy.context.active_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roy\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\TexTools_1_6_1\op_meshtex_create.py", line 78, in create_uv_mesh
    faces_by_island = utilities_uv.getSelectionIslands(bm, uv_layers, need_faces_selected=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roy\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\TexTools_1_6_1\utilities_uv.py", line 675, in getSelectionIslands
    selected_faces = {f for f in bm.faces if any([l[uv_layers].select for l in f.loops]) and f.select}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roy\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\TexTools_1_6_1\utilities_uv.py", line 675, in <setcomp>
    selected_faces = {f for f in bm.faces if any([l[uv_layers].select for l in f.loops]) and f.select}
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roy\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\TexTools_1_6_1\utilities_uv.py", line 675, in <listcomp>
    selected_faces = {f for f in bm.faces if any([l[uv_layers].select for l in f.loops]) and f.select}
                                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'BMLoopUV' object has no attribute 'select'

**Comment by unclepomedev** [comment]
I believe I've fixed this specific `AttributeError` in my **unofficial** release (v1.6.3).

The issue was caused by the removal of the `.select` attribute in Blender 5.0's Python API. I've updated the script to use the new selection method compatible with Blender 5.0+.

You can download the fixed version here: https://github.com/unclepomedev/TexTools-Blender/releases/tag/v1.6.3
I also fixed the Shape Keys morphing issue, so the slider should work correctly now.

**Comment by gulagenabler** [comment]
helloo , yeah so i installed it and get this error still

Python: Traceback (most recent call last):
  File "C:\Users\Roy\AppData\Roaming\Blender
Foundation\Blender\5.0\scripts\addons\TexTools\utilities_uv.py", line 583,
in getSelectionIslands
    getFacesIslands(bm, uv_layers, selected_faces, islands,
disordered_island_faces)
  File "C:\Users\Roy\AppData\Roaming\Blender
Foundation\Blender\5.0\scripts\addons\TexTools\utilities_uv.py", line 531,
in getFacesIslands
    bpy.ops.uv.select_all(action='DESELECT')
  File "D:\Blender 5\5.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.uv.select_all.poll() failed, context is
incorrect

**Comment by unclepomedev** [comment]
Hi,

Thanks for the report. Looking at the traceback, this appears to be a "Context" issue (Blender 5.0 seems much stricter with the API).
I'll try to fix this, so please wait for an update!

**Comment by gulagenabler** [comment]
Cheers bro, glad to hear

**Comment by unclepomedev** [comment]
Should be fixed now. Let me know if anything else comes up. 🙏 
It's manifest-based now, so please remove v1.6.3 first.

https://github.com/unclepomedev/TexTools-Blender/releases/tag/v1.6.4

**Comment by gulagenabler** [comment]
Ahhh you know what i think the issue is with ZenUV when you click the icon
to enter it it gives me that error but with blenders UV its fine.
